[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"

[program:fastapi]
command=uvicorn app:app --host 0.0.0.0 --port 8000 --workers 1
directory=/app/
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
environment=UPLOADS_DIR="%(ENV_UPLOADS_DIR)s",FLAG="%(ENV_FLAG)s"
